sudo: required
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

script:
  - docker build -t willwolfram18/aspnetcore-heroku .
  - docker tag willwolfram18/aspnetcore-heroku registry.heroku.com/$HEROKU_APP/web

deploy:
  provider: script
  script:
    docker push willwolfram18/aspnetcore-heroku;
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web -a $HEROKU_APP;
  on:
    branch: dev